-- PostgreSQL v6 import schema used only by convert_mariadb_dump.py.
-- The legacy warnings tables are intentional staging tables: plugin migration v7
-- copies their rows into punishments and removes them on the first startup.

CREATE TABLE IF NOT EXISTS schema_migrations (
    version integer PRIMARY KEY,
    description varchar(255) NOT NULL,
    applied_at timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS servers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name varchar(128) NOT NULL,
    game_port integer NOT NULL UNIQUE CHECK (game_port BETWEEN 1 AND 65535),
    created_at timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS players (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    steam_id varchar(32) NOT NULL UNIQUE,
    last_nickname varchar(64),
    statistics_private boolean NOT NULL DEFAULT false,
    referral_code varchar(16),
    created_at timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_players_referral_code ON players(referral_code);

CREATE TABLE IF NOT EXISTS account_links (
    player_id bigint PRIMARY KEY,
    discord_user_id varchar(20) NOT NULL UNIQUE,
    linked_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT fk_account_links_player FOREIGN KEY (player_id)
        REFERENCES players(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS referrals (
    invited_player_id bigint PRIMARY KEY,
    inviter_player_id bigint NOT NULL,
    accepted_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT fk_referrals_invited FOREIGN KEY (invited_player_id)
        REFERENCES players(id) ON DELETE CASCADE,
    CONSTRAINT fk_referrals_inviter FOREIGN KEY (inviter_player_id)
        REFERENCES players(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_referrals_inviter ON referrals(inviter_player_id);

CREATE TABLE IF NOT EXISTS warnings (
    server_id bigint NOT NULL,
    id bigint NOT NULL,
    player_id bigint NOT NULL,
    player_nickname varchar(64) NOT NULL,
    moderator_user_id varchar(64) NOT NULL,
    moderator_nickname varchar(64) NOT NULL,
    issued_at timestamp(6) without time zone NOT NULL,
    reason text NOT NULL,
    PRIMARY KEY (server_id, id),
    CONSTRAINT fk_warnings_server FOREIGN KEY (server_id)
        REFERENCES servers(id) ON DELETE CASCADE,
    CONSTRAINT fk_warnings_player FOREIGN KEY (player_id)
        REFERENCES players(id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_warnings_player ON warnings(server_id, player_id);

CREATE TABLE IF NOT EXISTS warning_sequences (
    server_id bigint PRIMARY KEY,
    next_id bigint NOT NULL DEFAULT 1,
    CONSTRAINT fk_warning_sequences_server FOREIGN KEY (server_id)
        REFERENCES servers(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS player_statistics (
    server_id bigint NOT NULL,
    player_id bigint NOT NULL,
    last_seen timestamp(6) without time zone NOT NULL,
    rounds_completed bigint NOT NULL DEFAULT 0,
    human_seconds bigint NOT NULL DEFAULT 0,
    scp_seconds bigint NOT NULL DEFAULT 0,
    spectator_seconds bigint NOT NULL DEFAULT 0,
    best_human_kills_round bigint NOT NULL DEFAULT 0,
    best_scp_kills_round bigint NOT NULL DEFAULT 0,
    longest_human_life_seconds bigint NOT NULL DEFAULT 0,
    longest_scp_life_seconds bigint NOT NULL DEFAULT 0,
    human_kills_as_human bigint NOT NULL DEFAULT 0,
    human_kills_as_scp bigint NOT NULL DEFAULT 0,
    scps_destroyed bigint NOT NULL DEFAULT 0,
    human_deaths bigint NOT NULL DEFAULT 0,
    scp_deaths bigint NOT NULL DEFAULT 0,
    classd_escapes_uncuffed bigint NOT NULL DEFAULT 0,
    fastest_classd_escape_uncuffed_seconds bigint,
    classd_escapes_cuffed bigint NOT NULL DEFAULT 0,
    fastest_classd_escape_cuffed_seconds bigint,
    scientist_escapes_uncuffed bigint NOT NULL DEFAULT 0,
    fastest_scientist_escape_uncuffed_seconds bigint,
    scientist_escapes_cuffed bigint NOT NULL DEFAULT 0,
    fastest_scientist_escape_cuffed_seconds bigint,
    classd_escorted bigint NOT NULL DEFAULT 0,
    scientist_escorted bigint NOT NULL DEFAULT 0,
    warhead_countdowns_started bigint NOT NULL DEFAULT 0,
    warhead_detonations bigint NOT NULL DEFAULT 0,
    warhead_countdowns_stopped bigint NOT NULL DEFAULT 0,
    pocket_entries bigint NOT NULL DEFAULT 0,
    pocket_escapes bigint NOT NULL DEFAULT 0,
    longest_pocket_seconds bigint NOT NULL DEFAULT 0,
    zombies_created bigint NOT NULL DEFAULT 0,
    generators_activated bigint NOT NULL DEFAULT 0,
    system_reboots_started bigint NOT NULL DEFAULT 0,
    tesla_kills_as_079 bigint NOT NULL DEFAULT 0,
    pink_candies_eaten bigint NOT NULL DEFAULT 0,
    best_snake_score bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (server_id, player_id),
    CONSTRAINT fk_player_statistics_server FOREIGN KEY (server_id)
        REFERENCES servers(id) ON DELETE CASCADE,
    CONSTRAINT fk_player_statistics_player FOREIGN KEY (player_id)
        REFERENCES players(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_player_statistics_last_seen
    ON player_statistics(server_id, last_seen);

CREATE TABLE IF NOT EXISTS server_statistics (
    server_id bigint PRIMARY KEY,
    rounds_completed bigint NOT NULL DEFAULT 0,
    total_round_seconds bigint NOT NULL DEFAULT 0,
    longest_round_seconds bigint NOT NULL DEFAULT 0,
    scp_wins bigint NOT NULL DEFAULT 0,
    foundation_wins bigint NOT NULL DEFAULT 0,
    chaos_wins bigint NOT NULL DEFAULT 0,
    draws bigint NOT NULL DEFAULT 0,
    warhead_detonations bigint NOT NULL DEFAULT 0,
    automatic_warhead_detonations bigint NOT NULL DEFAULT 0,
    player_warhead_detonations bigint NOT NULL DEFAULT 0,
    mtf_main_waves bigint NOT NULL DEFAULT 0,
    chaos_main_waves bigint NOT NULL DEFAULT 0,
    mtf_reinforcement_waves bigint NOT NULL DEFAULT 0,
    chaos_reinforcement_waves bigint NOT NULL DEFAULT 0,
    CONSTRAINT fk_server_statistics_server FOREIGN KEY (server_id)
        REFERENCES servers(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS legacy_imports (
    import_key varchar(191) PRIMARY KEY,
    imported_at timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);

CREATE OR REPLACE FUNCTION smoky_notify_player_statistics_changed()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM pg_notify(
        'smoky_player_statistics_changed',
        COALESCE(NEW.server_id, OLD.server_id)::text
    );
    RETURN COALESCE(NEW, OLD);
END
$$;

DROP TRIGGER IF EXISTS smoky_player_statistics_changed ON player_statistics;
CREATE TRIGGER smoky_player_statistics_changed
AFTER INSERT OR UPDATE OR DELETE ON player_statistics
FOR EACH ROW
EXECUTE PROCEDURE smoky_notify_player_statistics_changed();

CREATE OR REPLACE FUNCTION smoky_notify_statistics_privacy_changed()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.statistics_private IS DISTINCT FROM NEW.statistics_private THEN
        PERFORM pg_notify('smoky_player_statistics_changed', '*');
    END IF;
    RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS smoky_statistics_privacy_changed ON players;
CREATE TRIGGER smoky_statistics_privacy_changed
AFTER UPDATE OF statistics_private ON players
FOR EACH ROW
EXECUTE PROCEDURE smoky_notify_statistics_privacy_changed();
