namespace SmokyPluginV2
{
    using System.Collections.Generic;
    using System.ComponentModel;

    using Exiled.API.Interfaces;

    /// <summary>
    /// Plugin configuration generated by EXILED.
    /// </summary>
    public sealed class Config : IConfig
    {
        [Description("Whether the plugin is enabled.")]
        public bool IsEnabled { get; set; } = true;

        [Description("Whether debug messages should be shown in the server console.")]
        public bool Debug { get; set; } = false;

        [Description("Whether to restart an active round after the last player leaves the server.")]
        public bool RestartEmptyRound { get; set; } = true;

        [Description("Persistent player warning settings.")]
        public WarningSettings Warnings { get; set; } = new WarningSettings();

        [Description("Discord bot settings.")]
        public DiscordSettings Discord { get; set; } = new DiscordSettings();

        [Description("Individual game events that can be sent to the Discord game-events channel.")]
        public DiscordEventLogs DiscordEventLogs { get; set; } = new DiscordEventLogs();
    }

    public sealed class WarningSettings
    {
        [Description("Whether the persistent warning system and its Remote Admin commands are enabled.")]
        public bool IsEnabled { get; set; } = true;

        [Description("Whether an online player should receive a broadcast when warned.")]
        public bool NotifyPlayer { get; set; } = true;

        [Description("Warning broadcast duration in seconds.")]
        public ushort NotificationDuration { get; set; } = 30;

        [Description("Warning broadcast. Supports {id}, {reason}, and {moderator} placeholders.")]
        public string NotificationMessage { get; set; } = "Вы получили предупреждение\nПричина: {reason}";

        [Description("Maximum warning reason length.")]
        public int MaxReasonLength { get; set; } = 500;
    }

    public sealed class DiscordSettings
    {
        [Description("Whether the integrated Discord bot is enabled. The bot is not started while token is empty.")]
        public bool IsEnabled { get; set; } = true;

        [Description("Discord bot token. Keep this value secret.")]
        public string Token { get; set; } = string.Empty;

        [Description("Prefix reserved for text commands received from Discord.")]
        public string Prefix { get; set; } = "+";

        [Description("Discord server (guild) ID. Messages from other Discord servers are ignored.")]
        public ulong GuildId { get; set; }

        [Description("Channel ID for ordinary game-event logs.")]
        public ulong GameEventsChannelId { get; set; }

        [Description("Channel ID for every Remote Admin command.")]
        public ulong RemoteAdminChannelId { get; set; }

        [Description("Channel ID for moderation actions such as kicks, bans, mutes and warnings.")]
        public ulong ModerationChannelId { get; set; }

        [Description("How often the bot presence is refreshed, in seconds.")]
        public int StatusUpdateInterval { get; set; } = 30;

        [Description("Discord activity text. {players} and {max_players} are replaced automatically.")]
        public string StatusText { get; set; } = "{players} / {max_players} в игре";

        [Description("Whether the bot should listen for prefixed Discord messages. Required later for Discord commands.")]
        public bool ListenForCommands { get; set; } = true;

        [Description("Whether player IP addresses should be included in Discord join logs.")]
        public bool LogIpAddresses { get; set; } = true;

        [Description("Discord roles mapped to Remote Admin groups. Entries are checked from top to bottom; the first matching role has the highest priority.")]
        public List<DiscordRoleGroupMapping> RoleGroups { get; set; } = new List<DiscordRoleGroupMapping>
        {
            new DiscordRoleGroupMapping
            {
                DiscordRoleId = 0,
                RemoteAdminGroup = "owner",
            },
            new DiscordRoleGroupMapping
            {
                DiscordRoleId = 0,
                RemoteAdminGroup = "moderator",
            },
        };

        [Description("Steam-to-Discord account linking and role synchronization settings.")]
        public AccountLinkingSettings AccountLinking { get; set; } = new AccountLinkingSettings();
    }

    public sealed class AccountLinkingSettings
    {
        [Description("Whether slash-command account linking and Discord-to-SL role synchronization are enabled.")]
        public bool IsEnabled { get; set; } = true;

        [Description("How many minutes a one-time link code remains valid.")]
        public int CodeLifetimeMinutes { get; set; } = 5;

        [Description("Do not replace an RA group explicitly assigned to the Steam UserId in config_remoteadmin.txt.")]
        public bool PreserveNativeGroup { get; set; } = true;
    }

    public sealed class DiscordRoleGroupMapping
    {
        [Description("Discord role ID.")]
        public ulong DiscordRoleId { get; set; }

        [Description("Exact Remote Admin group name from config_remoteadmin.txt.")]
        public string RemoteAdminGroup { get; set; } = string.Empty;
    }

    public sealed class DiscordEventLogs
    {
        public bool WaitingForPlayers { get; set; } = true;
        public bool RoundStarted { get; set; } = true;
        public bool RoundEnded { get; set; } = true;
        public bool RespawnedMainWave { get; set; } = true;
        public bool RespawnedReinforcements { get; set; } = true;
        public bool PlayerReported { get; set; } = true;
        public bool PlayerJoined { get; set; } = true;
        public bool PlayerLeft { get; set; } = true;
        public bool PlayerHurt { get; set; } = true;
        public bool PlayerDied { get; set; } = true;
        public bool PlayerChangedRole { get; set; } = true;
        public bool PlayerChangedGroup { get; set; } = true;
        public bool PlayerChangedItem { get; set; } = true;
        public bool PlayerUsedItem { get; set; } = true;
        public bool PlayerThrewProjectile { get; set; } = true;
        public bool PlayerPickedUpItem { get; set; } = true;
        public bool PlayerDroppedItem { get; set; } = true;
        public bool PlayerReloadedWeapon { get; set; } = true;
        public bool PlayerEnteredPocketDimension { get; set; } = true;
        public bool PlayerEscapedPocketDimension { get; set; } = true;
        public bool PlayerUsedIntercom { get; set; } = true;
        public bool PlayerHandcuffed { get; set; } = true;
        public bool PlayerRemovedHandcuffs { get; set; } = true;
        public bool PlayerInteractedDoor { get; set; } = true;
        public bool PlayerInteractedElevator { get; set; } = true;
        public bool PlayerInteractedLocker { get; set; } = true;
        public bool PlayerTriggeredTesla { get; set; } = true;
        public bool PlayerAccessedWarheadPanel { get; set; } = true;
        public bool GeneratorUnlocked { get; set; } = true;
        public bool GeneratorOpened { get; set; } = true;
        public bool GeneratorClosed { get; set; } = true;
        public bool GeneratorActivationStarted { get; set; } = true;
        public bool GeneratorActivationStopped { get; set; } = true;
        public bool GeneratorActivated { get; set; } = true;
        public bool WarheadStarted { get; set; } = true;
        public bool WarheadStopped { get; set; } = true;
        public bool WarheadDetonated { get; set; } = true;
        public bool DecontaminationStarted { get; set; } = true;
        public bool Scp914Activated { get; set; } = true;
        public bool Scp914KnobChanged { get; set; } = true;
        public bool Scp914UpgradedItem { get; set; } = true;
        public bool Scp079GainedExperience { get; set; } = true;
        public bool Scp079GainedLevel { get; set; } = true;
        public bool Scp079UsedTesla { get; set; } = true;
        public bool Scp106Teleported { get; set; } = true;
        public bool Scp106EnteredStalking { get; set; } = true;
        public bool Scp106ExitedStalking { get; set; } = true;
    }
}
