namespace SmokyPluginV2
{
    using System.Collections.Generic;
    using System.ComponentModel;

    using Exiled.API.Interfaces;

    /// <summary>
    /// Plugin configuration generated by EXILED.
    /// </summary>
    public sealed class Config : IConfig
    {
        [Description("Whether the plugin is enabled.")]
        public bool IsEnabled { get; set; } = true;

        [Description("Whether debug messages should be shown in the server console.")]
        public bool Debug { get; set; } = false;

        [Description("Whether to restart an active round after the last player leaves the server.")]
        public bool RestartEmptyRound { get; set; } = true;

        [Description("MariaDB storage shared by statistics, account links and warnings.")]
        public DatabaseSettings Database { get; set; } = new DatabaseSettings();

        [Description("Persistent player and server statistics settings.")]
        public StatisticsSettings Statistics { get; set; } = new StatisticsSettings();

        [Description("Privileges earned from persistent player data.")]
        public EarnedPrivilegeSettings EarnedPrivileges { get; set; } = new EarnedPrivilegeSettings();

        [Description("Settings for enabling friendly fire only after a round has ended.")]
        public EndRoundFriendlyFireSettings EndRoundFriendlyFire { get; set; } = new EndRoundFriendlyFireSettings();

        [Description("Settings for spawning first-time late joiners into a human role near the beginning of a round.")]
        public LateJoinSpawnSettings LateJoinSpawn { get; set; } = new LateJoinSpawnSettings();

        [Description("Settings for restoring the pink candy to SCP-330's bowl.")]
        public PinkCandySettings PinkCandy { get; set; } = new PinkCandySettings();

        [Description("Settings for a recurring broadcast shown to every connected player.")]
        public GeneralBroadcastSettings GeneralBroadcast { get; set; } = new GeneralBroadcastSettings();

        [Description("Pre-round role preference UI and role assignment settings.")]
        public RolePreferenceSettings RolePreferences { get; set; } = new RolePreferenceSettings();

        [Description("Persistent player warning settings.")]
        public WarningSettings Warnings { get; set; } = new WarningSettings();

        [Description("Discord bot settings.")]
        public DiscordSettings Discord { get; set; } = new DiscordSettings();

        [Description("Individual game events that can be sent to the Discord game-events channel.")]
        public DiscordEventLogs DiscordEventLogs { get; set; } = new DiscordEventLogs();
    }

    public sealed class DatabaseSettings
    {
        [Description("Whether MariaDB persistence is enabled. Warnings, account links and statistics require it.")]
        public bool IsEnabled { get; set; } = true;

        [Description("Human-readable server name shown in statistics.")]
        public string ServerName { get; set; } = "Main server";

        [Description("Import legacy account-links.yml and warnings.yml once, then keep the YAML files as untouched backups.")]
        public bool ImportLegacyYaml { get; set; } = true;
    }

    public sealed class StatisticsSettings
    {
        [Description("Whether player and server statistics are collected during active rounds.")]
        public bool IsEnabled { get; set; } = true;

    }

    public sealed class EarnedPrivilegeSettings
    {
        [Description("Required total playtime in hours. Human, SCP and spectator time from statistics are included.")]
        public double RequiredHours { get; set; } = 100;

        [Description("Remote Admin group granted while the player meets the required playtime. The same group must be present in discord.role_groups.")]
        public string GroupName { get; set; } = "pearl";

        [Description("Referral program settings. The earned group above is also granted for enough qualified referrals.")]
        public ReferralSettings Referrals { get; set; } = new ReferralSettings();
    }

    public sealed class ReferralSettings
    {
        [Description("Whether the referral program is enabled.")]
        public bool IsEnabled { get; set; } = true;

        [Description("Maximum total playtime in minutes at which a player may enter a referral code.")]
        public int CodeEntryMaxMinutes { get; set; } = 15;

        [Description("Total network playtime in minutes required for an invited player to qualify.")]
        public int QualificationMinutes { get; set; } = 120;

        [Description("How many qualified referrals grant the earned privilege group.")]
        public int RequiredReferrals { get; set; } = 5;

        [Description("Temporary role-selection weight for an invited player until the referral qualifies.")]
        public double PendingReferralWeight { get; set; } = 1.25;
    }

    public sealed class GeneralBroadcastSettings
    {
        [Description("Whether the recurring server-wide broadcast is enabled.")]
        public bool IsEnabled { get; set; } = false;

        [Description("Delay in seconds between broadcasts.")]
        public float IntervalSeconds { get; set; } = 300f;

        [Description("How many seconds each broadcast remains visible.")]
        public ushort DurationSeconds { get; set; } = 10;

        [Description("Broadcast text. SCP:SL rich-text tags are supported.")]
        public string Text { get; set; } = "Добро пожаловать на сервер!";
    }

    public sealed class EndRoundFriendlyFireSettings
    {
        [Description("Whether friendly fire should be enabled after RoundEnded and disabled before the next round.")]
        public bool IsEnabled { get; set; } = true;
    }

    public sealed class LateJoinSpawnSettings
    {
        [Description("Whether first-time players may spawn after joining an active round.")]
        public bool IsEnabled { get; set; } = true;

        [Description("Latest allowed join time in seconds after the round starts.")]
        public double MaxJoinTimeSeconds { get; set; } = 120;

        [Description("Whether first-time players may spawn as a squad member after a main respawn wave.")]
        public bool SpawnAfterMainWaves { get; set; } = true;

        [Description("Latest allowed join time in seconds after a main MTF or Chaos wave. Reinforcement waves do not open or extend this window.")]
        public double MainWaveJoinTimeSeconds { get; set; } = 60;

        [Description("Delay before assigning the role, allowing player verification to finish.")]
        public float SpawnDelaySeconds { get; set; } = 1;

        [Description("Relative spawn chance for Class D. Default distribution: 37.5%.")]
        public double ClassDChance { get; set; } = 37.5;

        [Description("Relative spawn chance for Facility Guard. Default distribution: 37.5%.")]
        public double FacilityGuardChance { get; set; } = 37.5;

        [Description("Relative spawn chance for Scientist. Default distribution: 25%.")]
        public double ScientistChance { get; set; } = 25;
    }

    public sealed class PinkCandySettings
    {
        [Description("Whether SCP-330 can give players the pink candy.")]
        public bool IsEnabled { get; set; } = true;

        [Description("Chance in percent that a candy taken from SCP-330 is replaced with the pink candy.")]
        public double ChancePercent { get; set; } = 20;
    }

    public sealed class RolePreferenceSettings
    {
        [Description("Whether players can submit round-start role preferences in the pre-round tower.")]
        public bool IsEnabled { get; set; } = true;

        [Description("Pre-round tower selection settings.")]
        public RolePreferenceTowerSettings Tower { get; set; } = new RolePreferenceTowerSettings();

        [Description("Relative selection weight for players whose group is not present in priority_tiers.")]
        public double DefaultWeight { get; set; } = 1;

        [Description("Priority tiers. All currently resolved Remote Admin groups are matched case-insensitively; the highest-weight match wins.")]
        public List<RolePreferencePriorityTier> PriorityTiers { get; set; } = new List<RolePreferencePriorityTier>
        {
            new RolePreferencePriorityTier
            {
                Name = "sponsor",
                Weight = 2.5,
                Groups = new List<string> { "sponsor" },
            },
            new RolePreferencePriorityTier
            {
                Name = "premium",
                Weight = 2,
                Groups = new List<string> { "premium" },
            },
            new RolePreferencePriorityTier
            {
                Name = "vip",
                Weight = 1.5,
                Groups = new List<string> { "vip" },
            },
        };
    }

    public sealed class RolePreferenceTowerSettings
    {
        [Description("Whether players should spawn as Tutorial in the tower and select a class by standing in a colored zone.")]
        public bool IsEnabled { get; set; } = true;

        [Description("Whether zone positions should be calculated from the current native Tutorial spawn and the surrounding room walls.")]
        public bool UseDynamicZonePositions { get; set; } = true;

        [Description("Gap in meters between a dynamically sized zone edge and each adjacent room wall.")]
        public float DynamicZoneWallGap { get; set; } = 0.18f;

        [Description("Walkway gap in meters between dynamically sized zones.")]
        public float DynamicZoneCenterGap { get; set; } = 0.5f;

        [Description("Scale applied to the largest square zones that fit the measured room. Values below 1 make the zones smaller while keeping them in the corners.")]
        public float DynamicZoneSizeScale { get; set; } = 0.85f;

        [Description("Fallback tower center used only when dynamic zone positioning is disabled.")]
        public RolePreferencePoint Center { get; set; } = new RolePreferencePoint(53.6f, 1018.4f, -44.6f);

        [Description("Center of the red SCP selection zone.")]
        public RolePreferencePoint ScpZone { get; set; } = new RolePreferencePoint(50.9f, 1018.15f, -40.7f);

        [Description("Center of the yellow Scientist selection zone.")]
        public RolePreferencePoint ScientistZone { get; set; } = new RolePreferencePoint(56.3f, 1018.15f, -40.7f);

        [Description("Center of the orange Class D selection zone.")]
        public RolePreferencePoint ClassDZone { get; set; } = new RolePreferencePoint(50.9f, 1018.15f, -48.5f);

        [Description("Center of the blue Facility Guard selection zone.")]
        public RolePreferencePoint FacilityGuardZone { get; set; } = new RolePreferencePoint(56.3f, 1018.15f, -48.5f);

        [Description("Half-size of each square selection zone in meters.")]
        public float ZoneRadius { get; set; } = 1.4f;

        [Description("Lobby countdown text. Supports {time}.")]
        public string LobbyTimerCountdown { get; set; } = "Раунд начнется через {time} секунд";

        [Description("Text shown while the native lobby countdown is paused.")]
        public string LobbyTimerRoundPaused { get; set; } = "Запуск раунда приостановлен";

        [Description("Text shown while the round is starting.")]
        public string LobbyTimerRoundStarting { get; set; } = "Раунд начинается!";

        [Description("Connected-player text. Supports {players}.")]
        public string LobbyTimerPlayersConnected { get; set; } = "{players} игроков подключилось";

        [Description("Displayed name for a random role selection.")]
        public string RandomRoleName { get; set; } = "Случайно";

        [Description("Displayed name for the SCP role category.")]
        public string ScpRoleName { get; set; } = "SCP";

        [Description("Displayed name for the Scientist role category.")]
        public string ScientistRoleName { get; set; } = "Научный Сотрудник";

        [Description("Displayed name for the Class D role category.")]
        public string ClassDRoleName { get; set; } = "Персонал класса D";

        [Description("Displayed name for the Facility Guard role category.")]
        public string FacilityGuardRoleName { get; set; } = "Охранник Комплекса";

        [Description("Selected-class hint line. Supports {role} and {color}.")]
        public string SelectedClassText { get; set; } = "Выбранный класс: <color={color}><b>{role}</b></color>";

        [Description("Probability hint line. Supports {probability}.")]
        public string ProbabilityText { get; set; } = "Вероятность: <b>{probability}</b>";

        [Description("Contested-selection hint line. Supports {requested}, {slots}, and {weight}.")]
        public string CompetitionText { get; set; } = "Желающих: {requested} · мест: {slots} · вес: {weight}";

        [Description("Hint line shown while the player's class is random.")]
        public string RandomInstructionText { get; set; } = "Войдите в одну из четырёх цветных зон";

        [Description("Event briefing lobby lock, voice restriction, and hint settings.")]
        public EventBriefingSettings EventBriefing { get; set; } = new EventBriefingSettings();

    }

    public sealed class EventBriefingSettings
    {
        [Description("Whether the eventlobby Remote Admin command is enabled.")]
        public bool IsEnabled { get; set; } = true;

        [Description("Hint line replacing the selected class while the event briefing is active.")]
        public string AnnouncementText { get; set; } = "В этом раунде проводится ивент";

        [Description("Remote Admin groups whose players may speak during the event briefing.")]
        public List<string> MuteExemptGroups { get; set; } = new List<string> { "owner", "admin" };
    }

    public sealed class RolePreferencePoint
    {
        public RolePreferencePoint()
        {
        }

        public RolePreferencePoint(float x, float y, float z)
        {
            X = x;
            Y = y;
            Z = z;
        }

        public float X { get; set; }

        public float Y { get; set; }

        public float Z { get; set; }
    }

    public sealed class RolePreferencePriorityTier
    {
        [Description("Human-readable tier name used in logs and confirmations.")]
        public string Name { get; set; } = string.Empty;

        [Description("Relative weight used only when more players request a role than there are slots.")]
        public double Weight { get; set; } = 1;

        [Description("Remote Admin group names included in this tier.")]
        public List<string> Groups { get; set; } = new List<string>();

    }

    public sealed class WarningSettings
    {
        [Description("Whether the persistent warning system and its Remote Admin commands are enabled.")]
        public bool IsEnabled { get; set; } = true;

        [Description("Whether an online player should receive a broadcast when warned.")]
        public bool NotifyPlayer { get; set; } = true;

        [Description("Warning broadcast duration in seconds.")]
        public ushort NotificationDuration { get; set; } = 30;

        [Description("Warning broadcast. Supports {id}, {reason}, and {moderator} placeholders.")]
        public string NotificationMessage { get; set; } = "Вы получили предупреждение\nПричина: {reason}";

        [Description("Maximum warning reason length.")]
        public int MaxReasonLength { get; set; } = 500;
    }

    public sealed class DiscordSettings
    {
        [Description("Whether the integrated Discord bot is enabled. The bot is not started while token is empty.")]
        public bool IsEnabled { get; set; } = true;

        [Description("Discord bot token. Keep this value secret.")]
        public string Token { get; set; } = string.Empty;

        [Description("Prefix reserved for text commands received from Discord.")]
        public string Prefix { get; set; } = "+";

        [Description("Discord server (guild) ID. Messages from other Discord servers are ignored.")]
        public ulong GuildId { get; set; }

        [Description("Channel ID for ordinary game-event logs.")]
        public ulong GameEventsChannelId { get; set; }

        [Description("Channel ID for every Remote Admin command.")]
        public ulong RemoteAdminChannelId { get; set; }

        [Description("Channel ID for moderation actions such as kicks, bans, mutes and warnings.")]
        public ulong ModerationChannelId { get; set; }

        [Description("How often the bot presence is refreshed, in seconds.")]
        public int StatusUpdateInterval { get; set; } = 30;

        [Description("Discord activity text. {players} and {max_players} are replaced automatically.")]
        public string StatusText { get; set; } = "{players} / {max_players} в игре";

        [Description("Whether the bot should listen for prefixed Discord messages. Required later for Discord commands.")]
        public bool ListenForCommands { get; set; } = true;

        [Description("Whether player IP addresses should be included in Discord join logs.")]
        public bool LogIpAddresses { get; set; } = true;

        [Description("Discord roles mapped to Remote Admin groups. Entries are checked from top to bottom; the first matching role has the highest priority.")]
        public List<DiscordRoleGroupMapping> RoleGroups { get; set; } = new List<DiscordRoleGroupMapping>
        {
            new DiscordRoleGroupMapping
            {
                DiscordRoleId = 0,
                RemoteAdminGroup = "owner",
            },
            new DiscordRoleGroupMapping
            {
                DiscordRoleId = 0,
                RemoteAdminGroup = "moderator",
            },
        };

        [Description("Steam-to-Discord account linking and role synchronization settings.")]
        public AccountLinkingSettings AccountLinking { get; set; } = new AccountLinkingSettings();
    }

    public sealed class AccountLinkingSettings
    {
        [Description("Whether slash-command account linking and Discord-to-SL role synchronization are enabled.")]
        public bool IsEnabled { get; set; } = true;

        [Description("How many minutes a one-time link code remains valid.")]
        public int CodeLifetimeMinutes { get; set; } = 5;

        [Description("Discord role granted while a Steam account is linked. Set to 0 to disable. A matching discord.role_groups entry is optional.")]
        public ulong LinkedDiscordRoleId { get; set; } = 0;

        [Description("Do not replace an RA group explicitly assigned to the Steam UserId in config_remoteadmin.txt.")]
        public bool PreserveNativeGroup { get; set; } = true;
    }

    public sealed class DiscordRoleGroupMapping
    {
        [Description("Discord role ID.")]
        public ulong DiscordRoleId { get; set; }

        [Description("Exact Remote Admin group name from config_remoteadmin.txt.")]
        public string RemoteAdminGroup { get; set; } = string.Empty;
    }

    public sealed class DiscordEventLogs
    {
        public bool WaitingForPlayers { get; set; } = true;
        public bool RoundStarted { get; set; } = true;
        public bool RoundEnded { get; set; } = true;
        public bool RespawnedMainWave { get; set; } = true;
        public bool RespawnedReinforcements { get; set; } = true;
        public bool PlayerReported { get; set; } = true;
        public bool PlayerJoined { get; set; } = true;
        public bool PlayerLeft { get; set; } = true;
        public bool PlayerHurt { get; set; } = true;
        public bool PlayerDied { get; set; } = true;
        public bool PlayerChangedRole { get; set; } = true;
        public bool PlayerChangedGroup { get; set; } = true;
        public bool PlayerChangedItem { get; set; } = true;
        public bool PlayerUsedItem { get; set; } = true;
        public bool PlayerThrewProjectile { get; set; } = true;
        public bool PlayerPickedUpItem { get; set; } = true;
        public bool PlayerDroppedItem { get; set; } = true;
        public bool PlayerReloadedWeapon { get; set; } = true;
        public bool PlayerEnteredPocketDimension { get; set; } = true;
        public bool PlayerEscapedPocketDimension { get; set; } = true;
        public bool PlayerUsedIntercom { get; set; } = true;
        public bool PlayerHandcuffed { get; set; } = true;
        public bool PlayerRemovedHandcuffs { get; set; } = true;
        public bool PlayerInteractedDoor { get; set; } = true;
        public bool PlayerInteractedElevator { get; set; } = true;
        public bool PlayerInteractedLocker { get; set; } = true;
        public bool PlayerTriggeredTesla { get; set; } = true;
        public bool PlayerAccessedWarheadPanel { get; set; } = true;
        public bool GeneratorUnlocked { get; set; } = true;
        public bool GeneratorOpened { get; set; } = true;
        public bool GeneratorClosed { get; set; } = true;
        public bool GeneratorActivationStarted { get; set; } = true;
        public bool GeneratorActivationStopped { get; set; } = true;
        public bool GeneratorActivated { get; set; } = true;
        public bool WarheadStarted { get; set; } = true;
        public bool WarheadStopped { get; set; } = true;
        public bool WarheadDetonated { get; set; } = true;
        public bool DecontaminationStarted { get; set; } = true;
        public bool Scp914Activated { get; set; } = true;
        public bool Scp914KnobChanged { get; set; } = true;
        public bool Scp914UpgradedItem { get; set; } = true;
        public bool Scp079GainedExperience { get; set; } = true;
        public bool Scp079GainedLevel { get; set; } = true;
        public bool Scp079UsedTesla { get; set; } = true;
        public bool Scp106Teleported { get; set; } = true;
        public bool Scp106EnteredStalking { get; set; } = true;
        public bool Scp106ExitedStalking { get; set; } = true;
    }
}
